# Generated by Django 3.2.5 on 2021-08-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=30)),
                ('lweek', models.IntegerField()),
                ('lall', models.IntegerField()),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
                ('youtube', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
