# Generated by Django 3.2.5 on 2021-08-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
