# Generated by Django 4.0 on 2022-02-11 22:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_delete_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='age',
            field=models.CharField(max_length=30, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lall',
            field=models.IntegerField(verbose_name='Всего занятий'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lweek',
            field=models.IntegerField(verbose_name='Занятий в неделю'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='youtube',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на YouTube (если есть)'),
        ),
    ]
